# Quick deployment I like to use for troubleshooting k8s clusters
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-troubleshoot
  labels:
    app: k8s-troubleshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-troubleshoot
  template:
    metadata:
      labels:
        app: k8s-troubleshoot
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: foobar-service-account
      containers:
        - name: k8s-troubleshoot
          image: mcr.microsoft.com/azure-cli:latest
          command: ["sleep", "infinity"]
